<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NeutralLanguage>es-ES</NeutralLanguage>
    <Company>NODISLA</Company>
    <Authors>EA8DLF</Authors>
    <Product>Cuaderno NODISLA</Product>
    <Version>0.2.18</Version>
  </PropertyGroup>
</Project>
