<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nodisla.Cuaderno.Adif\Nodisla.Cuaderno.Adif.csproj" />
    <ProjectReference Include="..\..\src\Nodisla.Cuaderno.Datos\Nodisla.Cuaderno.Datos.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
