<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nodisla.Cuaderno.Dominio\Nodisla.Cuaderno.Dominio.csproj" />
    <ProjectReference Include="..\Nodisla.Cuaderno.Aplicacion\Nodisla.Cuaderno.Aplicacion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nodisla.Cuaderno.Adif.Pruebas" />
  </ItemGroup>

</Project>
