// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nodisla.Cuaderno.Datos;

#nullable disable

namespace Nodisla.Cuaderno.Datos.Migraciones
{
    [DbContext(typeof(ContextoCuaderno))]
    [Migration("20260921133443_CamposDeAntenaCondicionesYNaturaleza")]
    partial class CamposDeAntenaCondicionesYNaturaleza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.Estacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<double?>("MyAltitude")
                        .HasColumnType("REAL")
                        .HasColumnName("my_altitude");

                    b.Property<string>("MyAntenna")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_antenna");

                    b.Property<string>("MyCity")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_city");

                    b.Property<string>("MyCnty")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_cnty")
                        .UseCollation("NOCASE");

                    b.Property<string>("MyCountry")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_country")
                        .UseCollation("NOCASE");

                    b.Property<int?>("MyCqZone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("my_cq_zone");

                    b.Property<int?>("MyDxcc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("my_dxcc");

                    b.Property<string>("MyGridsquare")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("my_gridsquare")
                        .UseCollation("NOCASE");

                    b.Property<string>("MyIota")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_iota")
                        .UseCollation("NOCASE");

                    b.Property<int?>("MyItuZone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("my_itu_zone");

                    b.Property<double?>("MyLat")
                        .HasColumnType("REAL")
                        .HasColumnName("my_lat");

                    b.Property<double?>("MyLon")
                        .HasColumnType("REAL")
                        .HasColumnName("my_lon");

                    b.Property<string>("MyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_name");

                    b.Property<string>("MyPostalCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_postal_code");

                    b.Property<string>("MyRig")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_rig");

                    b.Property<string>("MySig")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_sig");

                    b.Property<string>("MySigInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_sig_info");

                    b.Property<string>("MyState")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_state")
                        .UseCollation("NOCASE");

                    b.Property<string>("MyStreet")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_street");

                    b.Property<string>("NombrePerfil")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_perfil")
                        .UseCollation("NOCASE");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT")
                        .HasColumnName("operator")
                        .UseCollation("NOCASE");

                    b.Property<string>("OwnerCallsign")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_callsign")
                        .UseCollation("NOCASE");

                    b.Property<bool>("Predeterminado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("predeterminado");

                    b.Property<string>("StationCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("station_callsign")
                        .UseCollation("NOCASE");

                    b.Property<double?>("TxPwrDefecto")
                        .HasColumnType("REAL")
                        .HasColumnName("tx_pwr_defecto");

                    b.HasKey("Id");

                    b.HasIndex("NombrePerfil")
                        .IsUnique()
                        .HasDatabaseName("ux_estacion_nombre");

                    b.ToTable("estacion", (string)null);
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.Qso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("AIndex")
                        .HasColumnType("REAL")
                        .HasColumnName("a_index");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<double?>("Age")
                        .HasColumnType("REAL")
                        .HasColumnName("age");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL")
                        .HasColumnName("altitude");

                    b.Property<double?>("AntAz")
                        .HasColumnType("REAL")
                        .HasColumnName("ant_az");

                    b.Property<double?>("AntEl")
                        .HasColumnType("REAL")
                        .HasColumnName("ant_el");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("band")
                        .UseCollation("NOCASE");

                    b.Property<string>("BandRx")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("band_rx")
                        .UseCollation("NOCASE");

                    b.Property<string>("Call")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("call")
                        .UseCollation("NOCASE");

                    b.Property<string>("Cnty")
                        .HasColumnType("TEXT")
                        .HasColumnName("cnty")
                        .UseCollation("NOCASE");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("Cont")
                        .HasColumnType("TEXT")
                        .HasColumnName("cont")
                        .UseCollation("NOCASE");

                    b.Property<string>("ContactedOp")
                        .HasColumnType("TEXT")
                        .HasColumnName("contacted_op")
                        .UseCollation("NOCASE");

                    b.Property<string>("ContestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contest_id")
                        .UseCollation("NOCASE");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasColumnName("country")
                        .UseCollation("NOCASE");

                    b.Property<int?>("Cqz")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cqz");

                    b.Property<string>("CreadoUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_utc");

                    b.Property<string>("DarcDok")
                        .HasColumnType("TEXT")
                        .HasColumnName("darc_dok")
                        .UseCollation("NOCASE");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL")
                        .HasColumnName("distance");

                    b.Property<int>("Dxcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("dxcc");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EqCall")
                        .HasColumnType("TEXT")
                        .HasColumnName("eq_call")
                        .UseCollation("NOCASE");

                    b.Property<long?>("EstacionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estacion_id");

                    b.Property<string>("FinUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("qso_fin_utc");

                    b.Property<double>("Freq")
                        .HasColumnType("REAL")
                        .HasColumnName("freq");

                    b.Property<double?>("FreqRx")
                        .HasColumnType("REAL")
                        .HasColumnName("freq_rx");

                    b.Property<string>("Gridsquare")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gridsquare")
                        .UseCollation("NOCASE");

                    b.Property<string>("GridsquareExt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gridsquare_ext")
                        .UseCollation("NOCASE");

                    b.Property<string>("InicioUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("qso_inicio_utc");

                    b.Property<string>("IotaIslandId")
                        .HasColumnType("TEXT")
                        .HasColumnName("iota_island_id");

                    b.Property<int?>("Ituz")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ituz");

                    b.Property<double?>("KIndex")
                        .HasColumnType("REAL")
                        .HasColumnName("k_index");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("REAL")
                        .HasColumnName("lon");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode")
                        .UseCollation("NOCASE");

                    b.Property<string>("ModificadoUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modificado_utc");

                    b.Property<double?>("MyAltitude")
                        .HasColumnType("REAL")
                        .HasColumnName("my_altitude");

                    b.Property<string>("MyAntenna")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_antenna");

                    b.Property<string>("MyCity")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_city");

                    b.Property<string>("MyCnty")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_cnty")
                        .UseCollation("NOCASE");

                    b.Property<string>("MyCountry")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_country")
                        .UseCollation("NOCASE");

                    b.Property<int?>("MyCqZone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("my_cq_zone");

                    b.Property<int?>("MyDxcc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("my_dxcc");

                    b.Property<string>("MyGridsquare")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("my_gridsquare")
                        .UseCollation("NOCASE");

                    b.Property<int?>("MyItuZone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("my_itu_zone");

                    b.Property<double?>("MyLat")
                        .HasColumnType("REAL")
                        .HasColumnName("my_lat");

                    b.Property<double?>("MyLon")
                        .HasColumnType("REAL")
                        .HasColumnName("my_lon");

                    b.Property<string>("MyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_name");

                    b.Property<string>("MyRig")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_rig");

                    b.Property<string>("MyState")
                        .HasColumnType("TEXT")
                        .HasColumnName("my_state")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT")
                        .HasColumnName("operator")
                        .UseCollation("NOCASE");

                    b.Property<string>("Origen")
                        .HasColumnType("TEXT")
                        .HasColumnName("origen")
                        .UseCollation("NOCASE");

                    b.Property<string>("OwnerCallsign")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_callsign")
                        .UseCollation("NOCASE");

                    b.Property<string>("Pfx")
                        .HasColumnType("TEXT")
                        .HasColumnName("pfx")
                        .UseCollation("NOCASE");

                    b.Property<string>("PropMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("prop_mode")
                        .UseCollation("NOCASE");

                    b.Property<string>("QslMsg")
                        .HasColumnType("TEXT")
                        .HasColumnName("qslmsg");

                    b.Property<string>("QslVia")
                        .HasColumnType("TEXT")
                        .HasColumnName("qsl_via")
                        .UseCollation("NOCASE");

                    b.Property<string>("QsoComplete")
                        .HasColumnType("TEXT")
                        .HasColumnName("qso_complete")
                        .UseCollation("NOCASE");

                    b.Property<bool?>("QsoRandom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qso_random");

                    b.Property<string>("Qth")
                        .HasColumnType("TEXT")
                        .HasColumnName("qth");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT")
                        .HasColumnName("region")
                        .UseCollation("NOCASE");

                    b.Property<string>("Rig")
                        .HasColumnType("TEXT")
                        .HasColumnName("rig");

                    b.Property<string>("RstRcvd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rst_rcvd");

                    b.Property<string>("RstSent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rst_sent");

                    b.Property<double?>("RxPwr")
                        .HasColumnType("REAL")
                        .HasColumnName("rx_pwr");

                    b.Property<string>("SatMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("sat_mode")
                        .UseCollation("NOCASE");

                    b.Property<string>("SatName")
                        .HasColumnType("TEXT")
                        .HasColumnName("sat_name")
                        .UseCollation("NOCASE");

                    b.Property<double?>("Sfi")
                        .HasColumnType("REAL")
                        .HasColumnName("sfi");

                    b.Property<bool>("SilentKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("silent_key");

                    b.Property<int?>("Srx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("srx");

                    b.Property<string>("SrxString")
                        .HasColumnType("TEXT")
                        .HasColumnName("srx_string");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("state")
                        .UseCollation("NOCASE");

                    b.Property<string>("StationCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("station_callsign")
                        .UseCollation("NOCASE");

                    b.Property<int?>("Stx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stx");

                    b.Property<string>("StxString")
                        .HasColumnType("TEXT")
                        .HasColumnName("stx_string");

                    b.Property<string>("Submodo")
                        .HasColumnType("TEXT")
                        .HasColumnName("submode")
                        .UseCollation("NOCASE");

                    b.Property<bool>("Swl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("swl");

                    b.Property<double?>("TxPwr")
                        .HasColumnType("REAL")
                        .HasColumnName("tx_pwr");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.Property<string>("Web")
                        .HasColumnType("TEXT")
                        .HasColumnName("web");

                    b.HasKey("Id");

                    b.HasIndex("Gridsquare")
                        .HasDatabaseName("ix_qso_grid")
                        .HasFilter("gridsquare <> ''");

                    b.HasIndex("InicioUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_qso_fecha");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ux_qso_uuid");

                    b.HasIndex("Call", "InicioUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_qso_call");

                    b.HasIndex("ContestId", "InicioUtc")
                        .HasDatabaseName("ix_qso_contest")
                        .HasFilter("contest_id IS NOT NULL");

                    b.HasIndex("Dxcc", "InicioUtc")
                        .HasDatabaseName("ix_qso_dxcc_fecha");

                    b.HasIndex("Dxcc", "State")
                        .HasDatabaseName("ix_qso_estado")
                        .HasFilter("state IS NOT NULL");

                    b.HasIndex("EstacionId", "InicioUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_qso_estacion");

                    b.HasIndex("Band", "Mode", "InicioUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_qso_band_mode_fecha");

                    b.HasIndex("Cqz", "Band", "Mode")
                        .HasDatabaseName("ix_qso_cq")
                        .HasFilter("cqz IS NOT NULL");

                    b.HasIndex("Dxcc", "Band", "Mode")
                        .HasDatabaseName("ix_qso_dxcc_band_mode");

                    b.HasIndex("Ituz", "Band", "Mode")
                        .HasDatabaseName("ix_qso_itu")
                        .HasFilter("ituz IS NOT NULL");

                    b.HasIndex("Call", "Band", "Mode", "InicioUtc")
                        .IsUnique()
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ux_qso_natural");

                    b.ToTable("qso", (string)null);
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.QsoCampoExtra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("campo")
                        .UseCollation("NOCASE");

                    b.Property<long>("QsoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qso_id");

                    b.Property<string>("TipoAdif")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_adif");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("QsoId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_campo_extra");

                    b.ToTable("qso_campo_extra", (string)null);
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.QsoConfirmacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Enviado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("enviada");

                    b.Property<string>("EnviadoUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_envio_utc");

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("servicio")
                        .UseCollation("NOCASE");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT")
                        .HasColumnName("nota");

                    b.Property<long>("QsoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qso_id");

                    b.Property<string>("Recibido")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recibida");

                    b.Property<string>("RecibidoUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_recep_utc");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("via_envio");

                    b.HasKey("Id");

                    b.HasIndex("QsoId", "Medio")
                        .IsUnique()
                        .HasDatabaseName("ux_conf_qso_servicio");

                    b.HasIndex("Medio", "Enviado", "QsoId")
                        .HasDatabaseName("ix_conf_servicio_env");

                    b.HasIndex("Medio", "Recibido", "QsoId")
                        .HasDatabaseName("ix_conf_servicio_rec");

                    b.ToTable("qso_confirmacion", (string)null);
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.QsoReferencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("referencia")
                        .UseCollation("NOCASE");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Lado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propia");

                    b.Property<string>("NombrePrograma")
                        .HasColumnType("TEXT")
                        .HasColumnName("programa")
                        .UseCollation("NOCASE");

                    b.Property<long>("QsoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qso_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("award_code")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("QsoId")
                        .HasDatabaseName("ix_ref_qso");

                    b.HasIndex("Lado", "Tipo", "Codigo")
                        .HasDatabaseName("ix_ref_propia");

                    b.HasIndex("Tipo", "Codigo", "Lado")
                        .HasDatabaseName("ix_ref_award_ref");

                    b.ToTable("qso_referencia", (string)null);
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.Qso", b =>
                {
                    b.HasOne("Nodisla.Cuaderno.Dominio.Entidades.Estacion", null)
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.QsoCampoExtra", b =>
                {
                    b.HasOne("Nodisla.Cuaderno.Dominio.Entidades.Qso", null)
                        .WithMany("CamposExtra")
                        .HasForeignKey("QsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.QsoConfirmacion", b =>
                {
                    b.HasOne("Nodisla.Cuaderno.Dominio.Entidades.Qso", null)
                        .WithMany("Confirmaciones")
                        .HasForeignKey("QsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.QsoReferencia", b =>
                {
                    b.HasOne("Nodisla.Cuaderno.Dominio.Entidades.Qso", null)
                        .WithMany("Referencias")
                        .HasForeignKey("QsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nodisla.Cuaderno.Dominio.Entidades.Qso", b =>
                {
                    b.Navigation("CamposExtra");

                    b.Navigation("Confirmaciones");

                    b.Navigation("Referencias");
                });
#pragma warning restore 612, 618
        }
    }
}
